#! /usr/bin/env ruby

require 'optparse'
require 'ostruct'
require 'pp'

class OptparseExample

  #
  # Return a structure describing the options.
  #
  def self.parse(args)
    # The options specified on the command line will be collected in *options*.
    # We set default values here.

    options = OpenStruct.new
    options.lowercase = false
    options.uppercase = false
    options.numbers = false
    options.special = false
    options.length = 10
    options.numbers_generated = 1
    options.pool = []

    opt_parser = OptionParser.new do |opts|
      opts.banner = "Usage: genpas [options]"

      opts.separator ""
      opts.separator "Specific options:"

      opts.on("number", "Characters generated") do |n|
      end

      opts.on("-l", "Include Lowercase") do |ext|
        options.lowercase = true
        options.pool += ("a".."z").to_a
      end

      opts.on("-u", "Include Uppercase") do |ext|
        options.uppercase = true
        options.pool += ("A".."Z").to_a
      end

      opts.on("-n", "Include Numbers") do |ext|
        options.numbers = true
        options.pool += ("0".."9").to_a
      end

      opts.on("-s", "Include Special Characters") do |ext|
        options.special = true
        options.pool += [",",".","!","?","@","&","%"]
      end

      opts.separator ""
      opts.separator "Example: "
      opts.separator "- 'genpas' prints 1 string of 10 chars with Lowercase, Uppercase and Numbers"
      opts.separator "- 'genpas -luns' prints 1 string of 10 chars with Lowercase, Uppercase, Numbers and Special Characters"
      opts.separator "- 'genpas 15' prints 1 string of 15 chars with Lowercase, Uppercase and Numbers"
      opts.separator "- 'genpas 20 2' prints 2 strings of 20 chars with Lowercase, Uppercase and Numbers"
      opts.separator "- 'genpas 25 -luns' prints a string of 25 chars with Lowercase, Uppercase, Numbers and Special Characters"
      opts.separator "- 'genpas 15 -luns 2' prints 2 strings of 15 chars with Lowercase, Uppercase, Numbers and Special Characters"

      opts.separator ""
      opts.separator "Common options:"

      # No argument, shows at tail.  This will print an options summary.
      # Try it and see!
      opts.on_tail("-h", "--help", "Show this message") do
        puts opts
        exit
      end

    end

    if (args.size == 0 || args.size == 1 && args[0].to_i.to_s == args[0])
      options.lowercase = true
      options.pool += ("a".."z").to_a
      options.uppercase = true
      options.pool += ("A".."Z").to_a
      options.numbers = true
      options.pool += ("0".."9").to_a
    end

    if args[0].to_i.to_s == args[0]
      numerical = args.shift
      options.length = numerical.to_i
    end

    if args.last.to_i.to_s == args.last
      numbers_generated = args.pop.to_i
      options.numbers_generated = numbers_generated
      if args.size == 0
        options.lowercase = true
        options.pool += ("a".."z").to_a
        options.uppercase = true
        options.pool += ("A".."Z").to_a
        options.numbers = true
        options.pool += ("0".."9").to_a
      end
    end

    opt_parser.parse!(args)
    return options
  end  # parse()

end  # class OptparseExample

def generate(number, pool)
  a = Random.new
  i = 0
  password = ""
  while i < number
    idx = a.rand(pool.size)
    password += pool[idx]
    i += 1
  end
  return password
end

options = OptparseExample.parse(ARGV)
pool = options.pool
length = options.length
numbers_gen = options.numbers_generated

if numbers_gen == 1
  puts generate(length, pool)
else
  numbers_gen.times do |n|
    puts (n+1).to_s + ". " + generate(length, pool)
  end
end
